# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eurochat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eurochat

  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'GoogleSignIn'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'FBSDKLoginKit'
  
  pod 'Picker', :path => '../node_modules/react-native-picker'


  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  pod 'RNSensors', :path => '../node_modules/react-native-sensors'

  pod 'react-native-geocoder', :path => '../node_modules/react-native-geocoder'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  target 'eurochatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'eurochat-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eurochat-tvOS

  target 'eurochat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
